version: "3.7"

services:
  risotto:
    container_name: risotto-mount
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: risotto-mount
    environment:
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/risotto
    stdin_open: true
    tty: true
  
  zero-shot:
    container_name: zero-shot-local
    build:
      context: .
      dockerfile: streamlit_apps/Dockerfile
    image: zero-shot
    environment:
      - ARTIFACT_NAME=zero_shot_artifacts.hdf
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/zero-shot
      - ./models-cache:/root/.cache/torch/
