version: "3.7"

services:
  lets-nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - ./lets-nginx/cache:/cache
      - ./lets-nginx/letsencrypt:/etc/letsencrypt
    environment:
      - EMAIL=${LETS_ENCRYPT_EMAIL}
      - DOMAIN=${LETS_ENCRYPT_DOMAIN}
      - STAGING=${LETS_ENCRYPT_STAGING}
      - UPSTREAM=risotto:8080
    depends_on:
      - risotto
    ports:
      - "80:80"
      - "443:443"

  risotto:
    container_name: risotto
    build:
      context: .
      dockerfile: Dockerfile
    image: risotto
    environment:
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
      - PORT=8080
    volumes:
      - ./datasets:/usr/src/risotto/datasets/
      - ./artifacts:/usr/src/risotto/artifacts/
    ports:
      - "8080"
    stdin_open: true
    tty: true

  zero-shot:
    container_name: zero-shot-local
    build:
      context: .
      dockerfile: streamlit_apps/Dockerfile
    image: zero-shot
    environment:
      - ARTIFACT_NAME=zero_shot_artifacts.hdf
    volumes:
      - ./models-cache:/root/.cache/torch/
