version: "3.7"

services:
  risotto:
    container_name: risotto
    build:
      context: .
      dockerfile: Dockerfile
    image: risotto
    environment:
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./datasets:/usr/src/risotto/datasets/
      - ./artifacts:/usr/src/risotto/artifacts/
    stdin_open: true
    tty: true
