version: "3.7"

services:
  risotto:
    container_name: risotto-mount
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: risotto-mount
    environment:
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/risotto
    stdin_open: true
    tty: true
