name: Update-Docs
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install the library
      run: |
        pip install nbdev jupyter
        pip install -e .
    - name: Update library
      run: |
        nbdev_build_lib
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
    - name: Rerun index.ipynb
      run: |
        jupyter nbconvert --to notebook --output index.ipynb --execute index.ipynb
    - name: Update readme
      run: |
        nbdev_build_docs
